# SQLite suffers from a "database is locked" race condition.
database:
    adapter: sqlite
    database: photohunt.sql

#database:
#    adapter: mysql2
#    host: db.csh.rit.edu
#    user: photohunt
#    password: apassword
#    database: photohunt

debug: false
